export const FOLLOW_ACTION = 'FOLLOW-ACTION-TYPE';
export const UNFOLLOW_ACTION = 'UNFOLLOW-ACTION-TYPE';
export const SET_USERS_ACTION = 'SET-USERS-ACTION';
export const SET_CURRENT_PAGE = 'SET-CURRENT-PAGE';
export const SET_TOTAL_COUNT = 'SET-TOTAL-COUNT';
export const TOGGLE_IS_FETCHING = 'TOGGLE-IS-FETCHING';
export const TOGGLE_IS_FOLLOWING_IN_PROGRESS = 'TOGGLE-IS-FOLLOWING-IN-PROGRESS';